# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeParkingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('parking_complexity', models.CharField(choices=[(0, 'unknown'), (1, 'newbie driver'), (2, 'accurate driver'), (3, 'experienced driver')], default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('owning_camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.AddField(
            model_name='freeparkingplace',
            name='owning_parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_parking_places', to='rest_api.Parking'),
        ),
    ]
