# Generated by Django 2.1.4 on 2019-01-13 12:18

from django.db import migrations, models
import rest_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_freeparkingplace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeparkingplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rest_api.models.images_path),
        ),
    ]
